### PR TITLE
upgrade to support (only) recent Django (1.8+) versions

### PR DESCRIPTION
**Pull request by zsoldosp**
plus added a single regression test and the test infrastructure

If old version support is needed, let me know, for now it was simpler to just drop old version support

### CODE REVIEW

**Comment by zsoldosp** [comment]
FYI: I've seen that you haven't updated the AUTHORS file, so I didn't add myself there either.

**Comment by belugame** [comment]
@zsoldosp I have only done some release work, so my contribution was trivial. This repo should actually be transfered to paesslerag github and pypi account. On pypi one can delete a package. Appears to me a re-publish from a different account should be possible then.

**Comment by zsoldosp** [comment]
Thanks for merging.

I wouldn't re-publish a package ever (IIRC some monthsago some crypto
library broke a ton of things that way :). I would rather not release this
version until it has been transferred to @paesslerag

**Comment by belugame** [comment]
yes, i agree with you. Since there will be at least a small time window of the package not being available on pypi, maybe we should play the delete-readd-package through on the staging server.

**Pull request merged**
